name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '15'
      - name: Run tests
        run: cd volunteer-organizer-backend && mvn test
      - name: Package
        run: cd volunteer-organizer-backend && mvn -Dmaven.test.skip=true package
#      - name: Try it!
#        run: java -cp target/kotlin-maven-1.0-SNAPSHOT-jar-with-dependencies.jar com.mycompany.app.App
